name: dev0
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - jupyter
  - opencv
  - pillow
  - seaborn
  - joblib
  - pip
  - pip:
    - yfinance
    - ta
    - tensorflow
    - keras